### PR TITLE
Fix in-toto chains docs typos

### PR DESCRIPTION
**Pull request by sublimino**

### CODE REVIEW

**Review by mattmoor — APPROVED** [review]

**Review by priyawadhwa — APPROVED** [review]
thanks!

**Comment by priyawadhwa** [comment]
hey @sublimino , I think you'll need to [sign the CLA](https://github.com/tektoncd/chains/pull/337#issuecomment-1015637026) and then this can be merged!

**Comment by sublimino** [comment]
Thanks @priyawadhwa, signed

**Comment by mattmoor** [comment]
@sublimino Can you try clicking through the big red thing above?  I think you need to kick it after the signing happens.

**Comment by sublimino** [comment]
Duly kicked @mattmoor 🙏

**Comment by mattmoor** [comment]
It is pretty wild that this ran everything without an `ok-to-test` label 🤔 

/ok-to-test

**Pull request merged**
