### PR TITLE
Corrected logic when token file provided

### LINKED ISSUE #1051: Inability to specify token file location
# Expected Behavior

Specifying the property `signers.x509.identity.token.file` should provide the capabilities for sourcing an identity token from the specified path. 

# Actual Behavior

When a file located at `/var/run/sigstore/cosign/oidc-token` (the default filepath) is present, the contents are used regardless of the value specified by the `signers.x509.identity.token.file` property

# Steps to Reproduce the Problem

1. Provide an identity token the location `/var/run/sigstore/cosign/oidc-token`
2. Provide another identity token at the location specified by the `signers.x509.identity.token.file` property
3. Specify the `signers.x509.identity.token.file` property in the `chains-config` ConfigMap
4. Run a Pipeline to trigger the Chains controller to sign content produced by the pipeline
5. The contents in the `/var/run/sigstore/cosign/oidc-token` is used regardless of the value defined in `signers.x509.identity.token.file`

# Additional Info

Tekton chains: 0.19.x
Kubernetes version: 1.27

### PR DESCRIPTION
**Pull request by sabre1041**
# Changes

Corrects an issue where the value specified by the `signers.x509.identity.token.file` is not observed when the default filepath is present in `/var/run/sigstore/cosign/oidc-token`

Resolves #1051

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

``` release-note
Corrects an issue to observe the path provided by the `signers.x509.identity.token.file` property even when the default filepath at `/var/run/sigstore/cosign/oidc-token` is present
```

### CODE REVIEW

**Review by lcarva — COMMENTED** [review]
Thanks for the fix! Could you add a unit test to help us prevent this from breaking again in the future?

**Review by lcarva — APPROVED** [review]

**Comment by lcarva** [comment]
Could you edit the commit message to link to the issue https://github.com/tektoncd/chains/issues/1051?

**Comment by sabre1041** [comment]
> Thanks for the fix! Could you add a unit test to help us prevent this from breaking again in the future?

Yes i will add testing

**Comment by sabre1041** [comment]
@lcarva Added a unit test

**Review by lcarva — APPROVED** [review]
/lgtm

**Pull request merged**
