### PR TITLE
Bump version of rekor to v0.5.0

### PR DESCRIPTION
**Pull request by robnester-rh**
Per a recent Sigstore blog post [1], it is recommended for all consumers
to migrate to a version of rekor >= 0.5.0 due to API and sharding
changes on the part of the rekor server. This commit bumps the version
to v0.5.0
[1] https://blog.sigstore.dev/sigstore-project-update-march-2022-bf34aa632388

Signed-off-by: Rob Nester <rnester@redhat.com>

### CODE REVIEW

**Review by lcarva — APPROVED** [review]

**Comment by lcarva** [comment]
/assign @mpeters

as suggested by tekton-robot.

**Comment by lcarva** [comment]
@wlynch, it looks like it needs an approval label.

**Comment by wlynch** [comment]
I can't approve (yet) :(

/approve

**Comment by wlynch** [comment]
cc @mattmoor @dlorenc for an assist?

**Comment by vdemeester** [comment]
approved 🙃

**Review by priyawadhwa — APPROVED** [review]
thanks for updating this!~

**Pull request merged**
