### PR TITLE
Add loosebazooka to chains approvers

### PR DESCRIPTION
**Pull request by loosebazooka**

### CODE REVIEW

**Comment by lukehinds** [comment]
Hey @loosebazooka 

I am not sure what the tekton community protocol is here, but would it be better to have you made a contribution first? 

p.s I think you would be great for the job, but I am guessing approvers should typically have made a PR to the project before.

Please do correct me if I am wrong (anyone)?

**Comment by loosebazooka** [comment]
Oh yeah, that's okay. I was just working with @priyawadhwa on some stuff.

**Review by priyawadhwa — APPROVED** [review]
amazing!

**Comment by priyawadhwa** [comment]
@lukehinds there should be a PR open soon!

**Pull request merged**
