### PR TITLE
Add lcarva, chuangw6 to global approvers.

### PR DESCRIPTION
**Pull request by wlynch**
# Changes

Adds @chuangw6 and @lcarva to global approvers.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by lcarva** [comment]
Thank you! :pray:

**Review by priyawadhwa — APPROVED** [review]
yay!

**Comment by bobcatfish** [comment]
Congrats to the new approvers!

@wlynch (and/or @lcarva @chuangw6 ) can you update the PR with some info around how these folks are meeting the contributor ladder maintainer requirements (https://github.com/tektoncd/community/blob/main/process.md#maintainer) ? (Or maybe this already exists and I'm missing it?) Thanks!

**Comment by wlynch** [comment]
This grants additional reviewer privileges (i.e. can /approve, but no direct write access, etc.), so I think there's no change w.r.t. [ladder requirements](https://github.com/tektoncd/community/blob/main/process.md#reviewer):

> Can be allowed to [/approve](https://github.com/tektoncd/community/blob/main/process.md#prow-commands) pull requests in specific sub-directories of a project (by maintainer discretion)

Updated the PR description above!

**Pull request merged**
