### PR TITLE
List the slsa/v2* formats in the in-toto set

### PR DESCRIPTION
**Pull request by lcarva**
# Changes

By listing the slsa/v2* payload formats in the in-toto attestation set, the storage backends are able to handle them properly. For example, without this change, the OCI backend ignores the slsa/v2alpha1 format altogether.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

``` release-note
NONE
```

### CODE REVIEW

**Comment by lcarva** [comment]
@chitrangpatel, your feedback here would be greatly appreciated! :pray:

**Review by wlynch — CHANGES_REQUESTED** [review]
One small change, but otherwise LGTM!

**Review by wlynch — APPROVED** [review]
/lgtm

**Pull request merged**
