### PR TITLE
Update k8s.io dependency to v0.23.5

### PR DESCRIPTION
**Pull request by priyawadhwa**
fixes https://github.com/tektoncd/chains/issues/408

### CODE REVIEW

**Comment by mattmoor** [comment]
I tagged you on a thread in slack related to these failures FYI.

**Comment by priyawadhwa** [comment]
this update also updates the `github.com/hashicorp/vault` dependency, which requires golang 1.17 otherwise it fails with this error:

```
Running tests with 'go test -race -v  ./... '
vendor/github.com/hashicorp/vault/sdk/helper/pluginutil/run_config.go:13:2: //go:build comment without // +build comment
//go:build comment without // +build comment
``` 

waiting on https://github.com/tektoncd/plumbing/pull/1047 to merge

**Comment by priyawadhwa** [comment]
waiting on https://github.com/tektoncd/plumbing/pull/1048/files

**Comment by priyawadhwa** [comment]
waiting on https://github.com/tektoncd/plumbing/pull/1049 to merge, should propagate within an hour once it's merged

**Review by mattmoor — APPROVED** [review]
/lgtm

**Pull request merged**
