### PR TITLE
Specify provider and oidc issuer when requesting fulcio cert

### PR DESCRIPTION
**Pull request by priyawadhwa**
Adds options for both of these to the config.

### CODE REVIEW

**Review by mattmoor — COMMENTED** [review]
/lgtm

Lotta deps being pulled in here, I assume sigstore update? 🤔

**Comment by priyawadhwa** [comment]
> Lotta deps being pulled in here, I assume sigstore update?

Yup, had to pull in cosign@main to be able to grab a specific provider!

**Comment by priyawadhwa** [comment]
@mattmoor i think you might need to add an /approve as well!

**Pull request merged**
