### PR TITLE
WIP: Add an intoto formatter.

### PR DESCRIPTION
**Pull request by dlorenc**
This translates TaskRuns to an InToto link format. Resources are mapped
to Products/Materials, and the TaskRun information is mapped to Environment.

Ref #12

### CODE REVIEW

**Comment by dlorenc** [comment]
This needs tests and documentation still, marking as WIP.

**Comment by lukehinds** [comment]
hey @dlorenc , that was quick!

Is there a reason for importing in-toto wholesale and not as a dependency in go.sum? (I am sure there must be, so curious).

**Comment by dlorenc** [comment]
> Is there a reason for importing in-toto wholesale and not as a dependency in go.sum? (I am sure there must be, so curious).

Good question! There are two main modes to work with go modules, vendoring and non vendoring. We're using vendoring here, so the code still gets committed.

I prefer vendoring, but it's not something every project does.

**Comment by shibumi** [comment]
> Good question! There are two main modes to work with go modules, vendoring and non vendoring. We're using vendoring here, so the code still gets committed. I prefer vendoring, but it's not something every project does.

Vendoring was useful before go.mod, right now it's fully ok to let go mod generate the vendor directory on demand and just push the go.mod and go.sum files to the project.

Btw, I am working on in-toto run support on in-toto-golang. This might be useful for you: https://github.com/in-toto/in-toto-golang/pull/56

I will definitely have a look on this PR here, too :)

**Comment by shibumi** [comment]
@dlorenc  do you know the state of this PR here? Is this PR deprecated?

**Comment by dlorenc** [comment]
> @dlorenc do you know the state of this PR here? Is this PR deprecated?

Yeah, this one is deprecated, it's being replaced by the ITE-6 formatter. The PR hasn't been opened yet, but you can see the branch and discussion in #65. I think @kommendorkapten is going to open it early next week!

**Comment by kommendorkapten** [comment]
@dlorenc @shibumi what Dan said, next week we should have a PR.

**Pull request closed without merging**
