### PR TITLE
Add boilerplate for e2e tests.

### PR DESCRIPTION
**Pull request by dlorenc**
This should be enough to get them setup in prow/plumbing.

Ref https://github.com/tektoncd/plumbing/pull/489

### CODE REVIEW

**Comment by dlorenc** [comment]
OK https://github.com/tektoncd/plumbing/pull/489 is in, I think it gets auto-applied to our cluster then I can iterate here until there's an empty test running and reporting results.

**Comment by vdemeester** [comment]
> OK [tektoncd/plumbing#489](https://github.com/tektoncd/plumbing/pull/489) is in, I think it gets auto-applied to our cluster then I can iterate here until there's an empty test running and reporting results.

Yep it does, might take a few minutes before applied but it should be there soon

**Comment by dlorenc** [comment]
Yesss! It's alive!

image

**Comment by dlorenc** [comment]
> Why does your editor strip newlines at EOF?

I think it was a copy/paste thing

**Pull request merged**
