### PR TITLE
Update release README

### PR DESCRIPTION
**Pull request by priyawadhwa**

### CODE REVIEW

**Comment by vaikas** [comment]
Hrm, looks like there might be some additional setup required, maybe a GCS object / bucket?

```

2021/09/25 16:35:53 os.Create(keyProfilePath)=/logs/artifacts/key-cov-prof.txt
2021/09/25 16:35:53 isPresubmit=true
2021/09/25 16:35:53 concerned Files=map[release/README.md:true]
2021/09/25 16:35:54 Running command 'go tool cover -html=/logs/artifacts/key-cov-prof.txt -o /logs/artifacts/line-cov.html'
2021/09/25 16:35:54 Finished running 'go tool cover -html=/logs/artifacts/key-cov-prof.txt -o /logs/artifacts/line-cov.html'
2021/09/25 16:35:54 cmd.Args=[go tool cover -html=/logs/artifacts/key-cov-prof.txt -o /logs/artifacts/line-cov.html]
2021/09/25 16:35:54 NewPostSubmit(Ctx, client StorageClient, ...) started
2021/09/25 16:35:54 end of ListGcsObjects(...)
2021/09/25 16:35:54 No build found for bucket 'tekton-prow' and object 'logs/post-tekton-chains-go-coverage'
```

**Comment by vaikas** [comment]
So, it's a bit odd, I see the artifacts being produced here (for example):
https://storage.googleapis.com/tekton-prow/pr-logs/pull/tektoncd_chains/240/pull-tekton-chains-go-coverage/1441803406883688448/artifacts/coverage_profile.txt

And:
https://storage.googleapis.com/tekton-prow/pr-logs/pull/tektoncd_chains/240/pull-tekton-chains-go-coverage/1441803406883688448/artifacts/stdout.txt

So, the coverage was ran, yay! I need to figure out where that error is coming from however :)

**Review by dlorenc — APPROVED** [review]

**Pull request merged**
