### PR TITLE
Bump tektoncd/pipelines dependency to v0.45

### PR DESCRIPTION
**Pull request by chitrangpatel**
Tektoncd/pipelines release v0.45 came with [some breaking changes](https://github.com/tektoncd/chains/issues/711). As a result, Chains needed to be updated. This PR
resolves those broken changes and updates to use tektoncd/pipeline v0.45.

# Changes
1. go dependency for tekton pipelines updated to v0.45.
2. Pipeline controller version in CI e2e test also bumped to v0.45. This is because while the API did not contain pipelineRun.Status.taskruns, the pipeline controller version(v0.40) was producing pipeline pipeline run.Status.Taskruns and causing integration test to fail. 
3. Fixed additional e2e test which came as a result of bumping Tekton pipelines controller to v0.45.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

``` release-note
Bump tektoncd/pipelines dependency to v0.45
```

### CODE REVIEW

**Review by wlynch — APPROVED** [review]
/lgtm

Big shout out to @lcarva for making sure we were ready for this change! 🙇 🙇 🙇

**Comment by chitrangpatel** [comment]
@wlynch to get the e2e tests working, I had to upgrade the CI pipelines controller to v0.45 as well (see PR description Changes for details). PTAL. If you're happy, it can now be lgtm-ed

**Review by wlynch — COMMENTED** [review]
LGTM pending response from pipeline maintainers for how they want to move forward with the breaking change (if the field ends up being rolled back we can keep the reconciler bits in to retain support for LTS versions). If no solid answer by EOW I'll merge this as-is.

**Comment by chitrangpatel** [comment]
> LGTM pending response from pipeline maintainers for how they want to move forward with the breaking change (if the field ends up being rolled back we can keep the reconciler bits in to retain support for LTS versions). If no solid answer by EOW I'll merge this as-is.

Sounds good!
/hold until EOW/reply from pipeline maintainers.

**Comment by wlynch** [comment]
Sounds like we're going to rollback the change in https://github.com/tektoncd/pipeline/pull/6206

https://github.com/tektoncd/chains/issues/716 to add running chains e2e tests against multiple Pipelines versions.

/hold cancel
/lgtm

**Pull request merged**
