### PR TITLE
Initial controller code.

### PR DESCRIPTION
**Pull request by dlorenc**
This stands up a controller using ko. The controller does nothing
right now, other than register watchers on TaskRuns and log
reconciliation events.

### CODE REVIEW

**Comment by font** [comment]
@dlorenc Is this mostly leveraged from `tektoncd/pipeline`? Would it be possible to split out the commit into generated and non-generated code?

**Comment by dlorenc** [comment]
> @dlorenc Is this mostly leveraged from `tektoncd/pipeline`? Would it be possible to split out the commit into generated and non-generated code?

So everything outside of vendor/ is non-generated. I think we can add a github config to hide these by default. I'll look into it.

**Comment by dlorenc** [comment]
> So everything outside of vendor/ is non-generated. I think we can add a github config to hide these by default. I'll look into it.

OK, I added the .gitattributes file to mark those as generated. Github should hide those now.

**Comment by font** [comment]
Thanks @dlorenc ! I was thinking for making it easier to review as GitHub won't show the entire diff, only the first 3000 changed files. But it looks like there's only 3 files (GitHub was smart enough to conveniently include them at the top) and the rest is generated.

/approve
/lgtm

**Pull request merged**
