### PR TITLE
Remove tekton as a provenance format

### PR DESCRIPTION
**Pull request by chitrangpatel**
This PR removes tekton as a provenance format since it was deprecated in an earlier release.

# Changes

1. Removes the directory `tekton` in `formats/`.
2. Updates all unit tests to point to `in-toto` instead of `tekton`.
3. Updated default format to `in-toto`.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

``` release-note
Remove tekton from supported provenance formats
```
/kind feature

### CODE REVIEW

**Review by wlynch — APPROVED** [review]
/lgtm

**Review by wlynch — CHANGES_REQUESTED** [review]
docs/config.md also needs to be updated.

**Comment by chitrangpatel** [comment]
> docs/config.md also needs to be updated.

Done!

**Review by wlynch — APPROVED** [review]
/lgtm

**Pull request merged**
