### PR TITLE
Handle duplicates in subjects and materials consistently

### PR DESCRIPTION
**Pull request by chuangw6**
# Changes

/kind bug

Fixes https://github.com/tektoncd/chains/issues/925

Prior, deduplication handling for subjects and materials is different.

Now, we use consistent approach to handle the deduplication.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)

# Release Notes

``` release-note
NONE
```

### CODE REVIEW

**Comment by chuangw6** [comment]
cc @lcarva could we possibly include this fix in the upcoming release? Thanks a lot!

**Comment by chuangw6** [comment]
[This failure](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_chains/926/pull-tekton-chains-unit-tests/1702800727983788032) seems like a flaky unit test 😮 
https://github.com/tektoncd/chains/blob/659b32b9867de8d7745527e345c3d14c20c570c9/pkg/chains/formats/slsa/v2alpha2/internal/external_parameters/external_parameters_test.go#L28-L48

In [the implementation](https://github.com/tektoncd/chains/blob/659b32b9867de8d7745527e345c3d14c20c570c9/pkg/chains/formats/slsa/v2alpha2/internal/external_parameters/external_parameters.go#L26-L38), it always gets the first entry in the map and the unit test assumes it's always the first entry in the test map. But golang maps are unordered data structure, so the first entry is non-deterministic. That's why the test is flaky. 


cc @joejstuart

**Comment by joejstuart** [comment]
> [This failure](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_chains/926/pull-tekton-chains-unit-tests/1702800727983788032) seems like a flaky unit test 😮
> 
> https://github.com/tektoncd/chains/blob/659b32b9867de8d7745527e345c3d14c20c570c9/pkg/chains/formats/slsa/v2alpha2/internal/external_parameters/external_parameters_test.go#L28-L48
> 
> In [the implementation](https://github.com/tektoncd/chains/blob/659b32b9867de8d7745527e345c3d14c20c570c9/pkg/chains/formats/slsa/v2alpha2/internal/external_parameters/external_parameters.go#L26-L38), it always gets the first entry in the map and the unit test assumes it's always the first entry in the test map. But golang maps are unordered data structure, so the first entry is non-deterministic. That's why the test is flaky.
> 
> cc @joejstuart

I'm unsure why the implementation only wants the first entry. It's existing code I moved. I'm wondering if we should just copy the whole `provenance.RefSource` to `externalParams["buildConfigSource"]`?

```diff
 // PipelineRun adds the pipeline run spec and provenance if available
 func PipelineRun(pro *objects.PipelineRunObject) map[string]any {
        externalParams := make(map[string]any)
 
        if provenance := pro.GetRemoteProvenance(); provenance != nil {
-               externalParams["buildConfigSource"] = buildConfigSource(provenance)
+               externalParams["buildConfigSource"] = provenance.RefSource
        }
        externalParams["runSpec"] = pro.Spec
        return externalParams
```

**Comment by chuangw6** [comment]
That's a good idea, but currently slsa defines the ref field for other ci/cd as string i.e. `workflow.ref` for [github](https://github.com/slsa-framework/github-actions-buildtypes/tree/main/workflow/v1#build-definition)

Maybe something we can flag to slsa team in this generic proposal? https://github.com/slsa-framework/slsa/issues/940

cc @chitrangpatel for thoughts.

**Comment by chitrangpatel** [comment]
> That's a good idea, but currently slsa defines the ref field for other ci/cd as string i.e. `workflow.ref` for [github](https://github.com/slsa-framework/github-actions-buildtypes/tree/main/workflow/v1#build-definition)
> 
> Maybe something we can flag to slsa team in this generic proposal? [slsa-framework/slsa#940](https://github.com/slsa-framework/slsa/issues/940)
> 
> cc @chitrangpatel for thoughts.

I think we should add it to the generic propossal. RefSource is a very Tekton Specific field. I think a more generic format for `cicd` based systems will be more useful for verifiers.

**Comment by joejstuart** [comment]
> > That's a good idea, but currently slsa defines the ref field for other ci/cd as string i.e. `workflow.ref` for [github](https://github.com/slsa-framework/github-actions-buildtypes/tree/main/workflow/v1#build-definition)
> > Maybe something we can flag to slsa team in this generic proposal? [slsa-framework/slsa#940](https://github.com/slsa-framework/slsa/issues/940)
> > cc @chitrangpatel for thoughts.
> 
> I think we should add it to the generic propossal. RefSource is a very Tekton Specific field. I think a more generic format for `cicd` based systems will be more useful for verifiers.

Here's a test that should work. https://github.com/tektoncd/chains/pull/928.

**Comment by chitrangpatel** [comment]
Thanks @chuangw6!

**Pull request merged**
