### PR TITLE
Bump go to 1.22 in actions workflows.

### PR DESCRIPTION
**Pull request by wlynch**
# Changes

Bump go to 1.22 in actions workflows.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

``` release-note
NONE
```

### CODE REVIEW

**Review by aaron-prindle — APPROVED** [review]

**Comment by aaron-prindle** [comment]
@wlynch, I've approved this PR - I believe now you can approve and merge IIUC as per the comment from prow/tekton-bot:

> To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from wlynch after the PR has been reviewed.

**Comment by wlynch** [comment]
I don't think I can self-approve.

/assign @chitrangpatel

**Review by lcarva — APPROVED** [review]

**Pull request merged**
