### PR TITLE
Remove sbwsg and dibyom from list of owners

### PR DESCRIPTION
**Pull request by sbwsg**
Original commit comment on the owners file says:

    This contains the initial approvers from
    https://docs.google.com/document/d/1dJjNTOXsT_dMZIX4i5iRw10fRQZBQqUP8YmbN2AwhAA/edit

That ain't me.

### CODE REVIEW

**Comment by bobcatfish** [comment]
@dibyom did you mean to be in there also?

**Comment by dibyom** [comment]
nope, totally ok with being removed as well 😄

**Comment by dlorenc** [comment]
Yeah sorry, I just noticed that today. I think I copied from pipelines and added the extra people, and forgot to remove you.

**Comment by dlorenc** [comment]
Looks like there's a conflict here.

**Comment by sbwsg** [comment]
Removed dibyom too and resolved the merge conflict.

**Pull request merged**
