### PR TITLE
Upgrade PipelineResourceTypeGit and PipelineResourceTypeImage to v1beta1 types

### PR DESCRIPTION
**Pull request by ywluogg**
Upgrade PipelineResourceTypeGit and PipelineResourceTypeImage to v1beta1 types

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes
Upgrade PipelineResourceTypeGit and PipelineResourceTypeImage to v1beta1 Pipeline types
``` release-note
NONE
```

### CODE REVIEW

**Comment by ywluogg** [comment]
#522

**Comment by piyush-garg** [comment]
this is not required, pipeline/v1alpha1 are removed, resource/v1alpha1 are not

**Comment by ywluogg** [comment]
> this is not required, pipeline/v1alpha1 are removed, resource/v1alpha1 are not

Ah yes, but I see a need that eventually we need to move to v1beta1 types, so opening this PR to convert those

**Comment by piyush-garg** [comment]
> > this is not required, pipeline/v1alpha1 are removed, resource/v1alpha1 are not
> 
> Ah yes, but I see a need that eventually we need to move to v1beta1 types, so opening this PR to convert those

That is for pipeline/v1alpha1, not resource/v1alpha1

**Comment by ywluogg** [comment]
Confirmed that Pipeline WG suggested to keep using resource/v1alpha1, so this is not necessary

**Pull request closed without merging**
