### PR TITLE
Bump rekor dependency to 0.10.

### PR DESCRIPTION
**Pull request by wlynch**
This is a pretty large, but overdue version bump of rekor.

(also bumps deps of other packages like cosign as a consequence).

This mirrors a hack introduced in
https://github.com/sigstore/policy-controller/pull/112 to fix a flag
name collision between glog and klog. Thanks @jdolitsky for the tip 🙏 

(p.s. vendored deps make PRs huge 😭 )

### CODE REVIEW

**Comment by wlynch** [comment]
@priyawadhwa underlying infra issues have be resolved - this is ready for review!

**Review by priyawadhwa — APPROVED** [review]

**Review by priyawadhwa — APPROVED** [review]

**Pull request merged**
