### PR TITLE
Bump knative/pkg and cosign dependencies

### PR DESCRIPTION
**Pull request by imjasonh**
Bumps to knative/pkg @ release-1.6 and cosign@latest (1.10.1)

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

``` release-note
NONE
```

### CODE REVIEW

**Comment by wlynch** [comment]
This is running into the same problem as https://github.com/tektoncd/chains/pull/514 😭 

We need Go 1.18 but the CI images are on 1.17. I made a PR to bump it, but it was causing issues with other tekton projects - https://tektoncd.slack.com/archives/CJ4ERJWAU/p1660211899070299 for

**Comment by imjasonh** [comment]
> This is running into the same problem as #514 😭
> 
> We need Go 1.18 but the CI images are on 1.17. I made a PR to bump it, but it was causing issues with other tekton projects - https://tektoncd.slack.com/archives/CJ4ERJWAU/p1660211899070299

Yeah, sounds like there's some ongoing work @abayer is doing to get us up onto 1.18. I'm going to stop pushing these things for now until these land.

**Comment by imjasonh** [comment]
```
--- FAIL: TestNoDeps (0.59s)
    --- FAIL: TestNoDeps/github.com/tektoncd/chains/cmd/controller (0.59s)
        depcheck.go:126: CheckNoDependency() = github.com/tektoncd/chains/cmd/controller depends on banned dependency github.com/golang/glog
            github.com/tektoncd/chains/cmd/controller
            github.com/tektoncd/chains/pkg/reconciler/taskrun
            github.com/tektoncd/chains/pkg/chains
            github.com/tektoncd/chains/pkg/chains/signing/x509
            github.com/sigstore/cosign/cmd/cosign/cli/fulcio  # Also: [github.com/sigstore/cosign/cmd/cosign/cli/options github.com/sigstore/cosign/pkg/cosign/git github.com/sigstore/cosign/pkg/cosign/git/github github.com/sigstore/cosign/pkg/cosign/git/gitlab github.com/sigstore/cosign/pkg/cosign/kubernetes github.com/sigstore/cosign/pkg/signature github.com/tektoncd/chains/pkg/chains github.com/tektoncd/chains/pkg/chains/signing/x509]
            github.com/sigstore/cosign/pkg/cosign
            github.com/sigstore/cosign/cmd/cosign/cli/fulcio/fulcioverifier/ctl
            github.com/google/certificate-transparency-go/x509util
            github.com/golang/glog
FAIL
FAIL	github.com/tektoncd/chains/cmd/controller	1.094s
FAIL
```

😭

**Comment by wlynch** [comment]
Closing this in favor of https://github.com/tektoncd/chains/pull/514

If there are more bumps you want to do, feel free to open another PR!

**Pull request closed without merging**
