### PR TITLE
Remove custom dependency version

### PR DESCRIPTION
**Pull request by rgreinho**
This patch aims at removing some custom dependency versions in order to
match the `cli` project.

### CODE REVIEW

**Comment by rgreinho** [comment]
While trying to integrate `chains` into the CLI, in https://github.com/tektoncd/cli/pull/1440, I got a lot of issues related to other dependencies. So my goal here is to try to align the dependencies between the two projects, mainly by removing these replacements and making sure the required versions match:

* k8s.io/api => k8s.io/api v0.21.4
* k8s.io/apimachinery => k8s.io/apimachinery v0.21.4
* k8s.io/client-go => k8s.io/client-go v0.21.4

However this breaks the tests and prevents the project to build.

```bash
go test ./...
# knative.dev/pkg/client/injection/kube/client
vendor/knative.dev/pkg/client/injection/kube/client/client.go:1236:9: cannot use &wrapAppsV1DeploymentImpl{...} (type *wrapAppsV1DeploymentImpl) as type "k8s.io/client-go/kubernetes/typed/apps/v1".DeploymentInterface in return argument:
	*wrapAppsV1DeploymentImpl does not implement "k8s.io/client-go/kubernetes/typed/apps/v1".DeploymentInterface (missing ApplyScale method)
vendor/knative.dev/pkg/client/injection/kube/client/client.go:1253:5: cannot use (*wrapAppsV1DeploymentImpl)(nil) (type *wrapAppsV1DeploymentImpl) as type "k8s.io/client-go/kubernetes/typed/apps/v1".DeploymentInterface in assignment:
	*wrapAppsV1DeploymentImpl does not implement "k8s.io/client-go/kubernetes/typed/apps/v1".DeploymentInterface (missing ApplyScale method)
vendor/knative.dev/pkg/client/injection/kube/client/client.go:1400:5: cannot use (*wrapAppsV1ReplicaSetImpl)(nil) (type *wrapAppsV1ReplicaSetImpl) as type "k8s.io/client-go/kubernetes/typed/apps/v1".ReplicaSetInterface in assignment:
	*wrapAppsV1ReplicaSetImpl does not implement "k8s.io/client-go/kubernetes/typed/apps/v1".ReplicaSetInterface (missing ApplyScale method)
vendor/knative.dev/pkg/client/injection/kube/client/client.go:1547:5: cannot use (*wrapAppsV1StatefulSetImpl)(nil) (type *wrapAppsV1StatefulSetImpl) as type "k8s.io/client-go/kubernetes/typed/apps/v1".StatefulSetInterface in assignment:
	*wrapAppsV1StatefulSetImpl does not implement "k8s.io/client-go/kubernetes/typed/apps/v1".StatefulSetInterface (missing ApplyScale method)
vendor/knative.dev/pkg/client/injection/kube/client/client.go:2697:5: cannot use (*wrapAppsV1beta2StatefulSetImpl)(nil) (type *wrapAppsV1beta2StatefulSetImpl) as type "k8s.io/client-go/kubernetes/typed/apps/v1beta2".StatefulSetInterface in assignment:
	*wrapAppsV1beta2StatefulSetImpl does not implement "k8s.io/client-go/kubernetes/typed/apps/v1beta2".StatefulSetInterface (missing ApplyScale method)
vendor/knative.dev/pkg/client/injection/kube/client/client.go:6049:5: cannot use (*wrapCoreV1PodImpl)(nil) (type *wrapCoreV1PodImpl) as type "k8s.io/client-go/kubernetes/typed/core/v1".PodInterface in assignment:
	*wrapCoreV1PodImpl does not implement "k8s.io/client-go/kubernetes/typed/core/v1".PodInterface (missing EvictV1 method)
vendor/knative.dev/pkg/client/injection/kube/client/client.go:6170:112: undefined: "k8s.io/api/core/v1".EphemeralContainers
vendor/knative.dev/pkg/client/injection/kube/client/client.go:6174:90: undefined: "k8s.io/api/core/v1".EphemeralContainers
vendor/knative.dev/pkg/client/injection/kube/client/client.go:7808:5: cannot use (*wrapExtensionsV1beta1DeploymentImpl)(nil) (type *wrapExtensionsV1beta1DeploymentImpl) as type "k8s.io/client-go/kubernetes/typed/extensions/v1beta1".DeploymentInterface in assignment:
	*wrapExtensionsV1beta1DeploymentImpl does not implement "k8s.io/client-go/kubernetes/typed/extensions/v1beta1".DeploymentInterface (missing ApplyScale method)
vendor/knative.dev/pkg/client/injection/kube/client/client.go:8368:5: cannot use (*wrapExtensionsV1beta1ReplicaSetImpl)(nil) (type *wrapExtensionsV1beta1ReplicaSetImpl) as type "k8s.io/client-go/kubernetes/typed/extensions/v1beta1".ReplicaSetInterface in assignment:
	*wrapExtensionsV1beta1ReplicaSetImpl does not implement "k8s.io/client-go/kubernetes/typed/extensions/v1beta1".ReplicaSetInterface (missing ApplyScale method)
vendor/knative.dev/pkg/client/injection/kube/client/client.go:1236:9: too many errors
```

I am not entirely sure how to fix this, therefore if I could get some pointers that would be greatly appreciated.

**Comment by dlorenc** [comment]
cc @mattmoor or @imjasonh  who might have some ideas

**Comment by mattmoor** [comment]
We need to bump knative’s K8s version, I believe.

**Comment by rgreinho** [comment]
> We need to bump knative’s K8s version, I believe.

Thanks @mattmoor for the suggestion. I just tried it with `go get -v -u knative.dev/pkg`:

```diff
$ git diff go.mod
diff --git a/go.mod b/go.mod
index 261c7928..cfa715ef 100644
--- a/go.mod
+++ b/go.mod
@@ -3,7 +3,7 @@ module github.com/tektoncd/chains
 go 1.16

 require (
-       cloud.google.com/go v0.97.0
+       cloud.google.com/go v0.98.0
        cloud.google.com/go/storage v1.18.2
        github.com/cenkalti/backoff/v3 v3.2.2 // indirect
        github.com/ghodss/yaml v1.0.0
@@ -34,13 +34,13 @@ require (
        go.uber.org/zap v1.19.1
        gocloud.dev v0.24.0
        golang.org/x/crypto v0.0.0-20210920023735-84f357641f63
-       google.golang.org/api v0.60.0
+       google.golang.org/api v0.61.0
        k8s.io/api v0.22.1
        k8s.io/apiextensions-apiserver v0.22.1 // indirect
        k8s.io/apimachinery v0.22.1
        k8s.io/client-go v0.22.1
        k8s.io/code-generator v0.22.1
-       knative.dev/pkg v0.0.0-20211123135150-787aec59e70a
+       knative.dev/pkg v0.0.0-20211216142117-79271798f696
 )
```

But I still get the same output as above when running the tests.

**Comment by mattmoor** [comment]
I mean knative/pkg needs this bumped because there are codegen changes needed.  I have a PR that needs rebasing.

**Comment by rgreinho** [comment]
Oh I see! Thanks for clarifying. I assume you are talking about this one: https://github.com/knative/pkg/pull/2327. I am going to follow it then 😉

**Comment by mattmoor** [comment]
FWIW, I don't think you should need that PR to integrate with the CLI, but I need to update that PR anyways, so I'm going to TAL at that right now.

**Comment by rgreinho** [comment]
Superseded by #316

**Pull request closed without merging**
