### PR TITLE
PipelineRuns with v2alpha4 to process StepActions

### PR DESCRIPTION
**Pull request by renzodavid9**
This new version will now process the information from any associated StepAction from the executed PipelineRun.

Also, the way chains read results from PipelineRuns to populate the `subjects` field is changing: now the user has to explicitly mark a result as a subject using an bject type-hinted tag (*ARTIFACT_OUTPUTS) + the new `isBuildArtifact` property in the value.

Refactors to share logic between v2alph3 and v2alpha4.

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

``` release-note
New v2alpha4 formatter for PipelineRuns that reads type-hinted result from associated StepActions
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/ok-to-test

**Comment by chitrangpatel** [comment]
Please fix the linter errors and add a release note.

**Comment by chitrangpatel** [comment]
Thanks for the cleanup Renzo! 

Happy to approve after fixing the linter error.

**Review by chitrangpatel — APPROVED** [review]
Thanks for you work on this Renzo! It wraps up support for StepResults as discussed in issue 
https://github.com/tektoncd/chains/issues/1065

**Pull request merged**
