### PR TITLE
Document the metrics provided by chains controller to fix #1041

### LINKED ISSUE #1041: Document the metrics provided by chains controller
### Feature request

At present, the Chains controller metrics aren't documented.  Document them so that end users can leverage them.

### PR DESCRIPTION
**Pull request by sudhishmk**
# Changes

Adding chains metrics documentation to fix issue #[1041](https://github.com/tektoncd/chains/issues/1041) 

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

``` release-note
NONE
```

### CODE REVIEW

**Review by savitaashture — COMMENTED** [review]
/lgtm

**Comment by khrm** [comment]
It seems there is some flake in integration tests. It fails a lot.

**Pull request merged**
