### PR TITLE
Includes visual guide representing chains config options

### PR DESCRIPTION
**Pull request by anithapriyanatarajan**
# Changes

Includes visual guide representing chains config options

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [X] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [X] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [X] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [X] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [X] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [X] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

``` release-note
NONE
```

### CODE REVIEW

**Comment by PuneetPunamiya** [comment]
Thanks for the pr 🙂 
This would really help the users I think

LGTM

**Comment by anithapriyanatarajan** [comment]
> Thanks for the pr 🙂 This would really help the users I think
> 
> LGTM

@PuneetPunamiya Thankyou. As you have highlighted the drawio.svg allows for future edit.

**Review by lcarva — APPROVED** [review]
/lgtm

This is great! Thank you so much :heart:

**Pull request merged**
